#
# Copyright (c) 2020 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.
#
javax:
    sql:
        DataSource:
            catalog-db:
                dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
                dataSource:
                    serverName: catalog-db
                    port: 3306
                    databaseName: catalog
                    user: catalog
                    password: pass
